### ISSUE TITLE
chop function will return an object with 0 positions when plane does not intersect geometry

### ISSUE THREAD

**Issue by kennethjiang** [kennethjiang/3tk#11]

**Comment by kennethjiang** [comment]
Hi @eyal0  Can you review my commit to fix this issue: https://github.com/kennethjiang/3tk/commit/eda5807e25a4c10b6d247b3832422f96705bdb7b ? 

In particular, I'm not sure how many `positiions` a mutator needs to have to be able to reconstruct a valid 3d object. I'm using `5` for now but it's very likely wrong.

**Comment by eyal0** [comment]
@kennethjiang Good question.  I have noticed that if I slice beyond the object, I get an empty result.

positions is like the positions in a BufferGeometry.  Each value is a floating point, every 3 is an (x,y,z), and every 3 (x,y,z) is a face.  The minimum faces for a valid shape should be a tetrahedron, 4 sides.  So positions should be at least 36 to be a shape, I think.

Good catch.

**Comment by kennethjiang** [comment]
If I understand the code correctly, after `disconnectAtSplit` is called, `fixPlanarHole` will be called to repair some shapes. Does it mean that more faces/positions may be added? If so, can a mutator have less than 36 positions *before* the repair? @eyal0
